// Public upstream test mnemonic. Never fund these accounts. This script cannot broadcast.
import fs from 'node:fs';
import init,{deriveAccount,verifyPayload} from '../public/crypto/quantus_browser_crypto.js';
import {Rpc,parseAmount,signingPayload,buildExtrinsic,verifyEnvelope,unhex,hex,concat,readCompact,validateMetadata} from '../lib/quantus/protocol.ts';
await init({module_or_path:fs.readFileSync(new URL('../public/crypto/quantus_browser_crypto_bg.wasm',import.meta.url))});
const mnemonic='orchard answer curve patient visual flower maze noise retreat penalty cage small earth domain scan pitch bottom crunch theme club client swap slice raven';
const client=new Rpc();const call=client.call.bind(client);client.call=async(method,params=[])=>{if(!['chain_getBlockHash','state_getRuntimeVersion','system_properties','chain_getHeader','system_accountNextIndex','state_getMetadata','state_getStorage','payment_queryInfo','state_call'].includes(method))throw new Error('Non-readonly RPC forbidden in test');return call(method,params);};
const report=[];
for(const scheme of ['ml-dsa-65','ml-dsa-87'] as const){const h=deriveAccount(mnemonic,scheme,0);try{const ctx=await client.context(h.address);const to=scheme==='ml-dsa-65'?'qzm5QCox8Dp5A3oSXZZYHD8YoYgPz7enykZb6RPUropdCyN5h':'qzoyC4eRTrexYoutXABVsf61QJZxJim3iWvayRQwEjXWgA4mw';const amount=parseAmount('0.001');const payload=signingPayload(ctx,to,amount);const signature=h.signPayload(payload,152);if(!verifyPayload(h.publicKey,payload,signature,scheme,152))throw new Error('Local verification failed');const tx=buildExtrinsic(ctx,h.address,to,amount,scheme,signature,h.publicKey);const hash=verifyEnvelope(tx,ctx,h.address,to,amount,scheme,signature,h.publicKey);const fee=await client.fee(tx);const registry=validateMetadata(ctx.metadataHex).registry;let simulation:unknown;let corrupt:unknown;try{const raw=await client.call<string>('state_call',['TaggedTransactionQueue_validate_transaction',hex(concat(Uint8Array.of(2),unhex(tx),unhex(ctx.blockHash))),ctx.blockHash]);simulation={raw,decoded:registry.createType('TransactionValidity',raw).toHuman()};const b=unhex(tx);const[,start]=readCompact(b);b[start+35]^=1;const bad=await client.call<string>('state_call',['TaggedTransactionQueue_validate_transaction',hex(concat(Uint8Array.of(2),b,unhex(ctx.blockHash))),ctx.blockHash]);corrupt={raw:bad,decoded:registry.createType('TransactionValidity',bad).toHuman()};}catch(e){simulation={available:false,error:e instanceof Error?e.message:String(e)};}report.push({scheme,address:h.address,hash,fee:fee.toString(),spec:ctx.spec,localSignatureVerified:true,simulation,corrupt});}finally{h.clear();h.free();}}
fs.writeFileSync(new URL('./fixtures/live-readonly-result.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
